FROM node:18

WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig.json ./
RUN npm install
RUN npm i -g typescript
RUN npm i -g pm2

COPY . .


RUN npm run build



CMD ["npm", "start"]

EXPOSE 3001
