name: Deploy

on:
  push:
    branches:
      - master 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout source
       uses: actions/checkout@v3

     - name: Login to Docker Hub
       run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

     - name: Build Docker image
       run: docker build -t kabir18/rollup ./backend
     - name: setting up env variables
       run: docker run -e SECRET=${{ secrets.SECRET }} \
                     -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
                     -e twiliono=${{ secrets.twiliono }} \
                     -e YOUR_TWILIO_ACCOUNT_SID=${{ secrets.YOUR_TWILIO_ACCOUNT_SID }} \
                     -e YOUR_TWILIO_AUTH_TOKEN=${{ secrets.YOUR_TWILIO_AUTH_TOKEN }} \
                     kabir18/rollup

     - name: Publish image to Docker Hub
       run: docker push kabir18/rollup:latest
 
     - name: SSH and deploy
       env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
       run: |
        echo "$SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile
        ssh -o StrictHostKeyChecking=no -v -t -i keyfile ubuntu@ec2-52-90-2-186.compute-1.amazonaws.com "sudo bash ~/docker.sh"
